server:
  port: 8899
  servlet:
    context-path: /webapi
  tomcat:
    uri-encoding: UTF-8

huanxin:
  base:
    info:
      app-key: 1110200407019890#m***
      org-name: 1110200*******
      app-name: mdchart
      client-id: YXA6SJ6e-zO3Q5-rAVgQZZ*******
      client-secret: YXA67FbU9fSAFIo*******
      server-domain: http://a1.easemob.com

qiniu:
  base:
    info:
      access_key: G4J2iQ8206CaAFdNL*******ZbiP6CGr
      secret_key: IdsmABe2qxwKK7*******CM2FY4V
      bucket: tiany*******mo
      domain: http://q4721qtc*******n.com
      file-prefix: userfiles
      file-base-dir: ${file.baseDir}
      user-header-prefix: /users/headers
      user-activity-prefix: /users/activity

spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/improgram?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      validation-query: select 1
      pool-prepared-statements: true
      max-open-prepared-statements: 20

debug: true

logging:
  level:
    root: debug

#mybatis:
#  mapper-locations: classpath*:mappers/**/*.xml

# 分页插件配置

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
